// =============================================================================
// Grafana Alloy — kube-state-metrics scrape config
// Generated by: make collector (when KSM_PORT is set in .env)
// DO NOT edit manually — regenerated on each `make collector` run.
//
// This file is only present on k3s/k8s control-plane collector nodes.
// Standard collector nodes have no k8s scrape block at all.
// =============================================================================

prometheus.scrape "kube_state_metrics" {
  targets = [
    {
      "__address__" = "localhost:" + env("KSM_PORT"),
      "node"        = env("NODE_NAME"),
      "cluster"     = env("CLUSTER_NAME"),
    },
  ]
  forward_to      = [prometheus.relabel.set_instance.receiver]
  job_name        = "kube-state-metrics"
  scrape_interval = "15s"
}
